#!/bin/bash

if [ ! -f /sys/class/gpio/gpio497/value ]; then
  echo 497 > /sys/class/gpio/export
  echo out > /sys/class/gpio/gpio497/direction
fi

echo 0 > /sys/class/gpio/gpio497/value && sleep 0.1
echo 1 > /sys/class/gpio/gpio497/value && sleep 0.1
rtk_hciattach /dev/ttyAML1 -s 115200 rtk_h5 115200

exit 0
