name: Test dispatch

on:
  repository_dispatch:
    types: ["hassos-dispatch"]

jobs:
  show-dispatch:
    name: Show dispatch event details
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
